name: "Metrics Monitor"
description: "Creates graphs of monitored values to display them using GitHub Pages."
branding:
  icon: "bar-chart"
  color: "blue"
inputs:
  token:
    description: "GitHub Token for pushing the doc changes"
    required: true
  key:
    description: "ket of value"
    required: true
  value:
    description: "indicator value"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}
    - ${{ inputs.key }}
    - ${{ inputs.value }}
