import * as React from "react";
import * as dayjs from "dayjs";
import * as pack from "../../../../package.json";

export const Footer: React.FC<{ date: Date }> = ({ date }) => (
  <div className="m-8">
    <p className="text-center">
      Last generated by{" "}
      <a
        href={pack.repository}
        className="font-bold"
      >
        <i className="fab fa-github"></i> {pack.name}
      </a>{" "}
      on {dayjs(date).format("lll")}.
    </p>
  </div>
);
