metrics:
  code-size:
    description: Size of all source files in KB
  files-count:
    description: Number of source files
  statement-coverage:
    description: Statement Coverage
  ci-time:
    description: CI run time
groups:
  general:
    name: General
    description: This section shows code complexity metrics
    metrics:
      - code-size
      - files-count
  tests:
    name: Testing
    description: This section shows code complexity metrics
    metrics:
      - statement-coverage
  ci:
    name: CI Data
    description: This section shows code complexity metrics
    metrics:
      - ci-time
  