name: Update Monitor

on:
  push:
    branches:
      - master

jobs:
  UpdateMonitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Build and Test
        id: projectmetrics
        run: |
          yarn
          yarn build
          yarn test
          SRC_SIZE=($(du -s src/))
          SRC_FILES_COUNT=($(find src -type f | wc -l))
          STATEMENT_COV=($(cat coverage/coverage-summary.json | jq ".total.statements.pct"))
          echo "::set-output name=code_size::$SRC_SIZE"
          echo "::set-output name=code_files_count::$SRC_FILES_COUNT"
          echo "::set-output name=statement-coverage::$STATEMENT_COV"
      - uses: ./
        name: Update Report for Files Size
        with:
          key: code-size
          value: ${{ steps.projectmetrics.outputs.code_size }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./
        name: Update Report for Files Count
        with:
          key: files-count
          value: ${{ steps.projectmetrics.outputs.code_files_count }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./
        name: Update Report for Statement Coverage
        with:
          key: statement-coverage
          value: ${{ steps.projectmetrics.outputs.statement-coverage }}
          token: ${{ secrets.GITHUB_TOKEN }}
